# Generated by Django 5.2.5 on 2025-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0028_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='cat_00',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_01',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_02',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_03',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_04',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_05',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_06',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_07',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_08',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_09',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_10',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_11',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_12',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_13',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_14',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_15',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_16',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_17',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_18',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='cat_19',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='tabs_to_delete',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='to_be_converted',
            field=models.BooleanField(default=False),
        ),
    ]
