# Generated by Django 5.2.5 on 2025-08-20 06:41

from django.db import migrations


def existing_classes_values(apps, schema_editor):
    """Sets values for existing classes"""
    ClassModel = apps.get_model("comptages", "Class")
    db_alias = schema_editor.connection.alias
    updates = [
        {
            "name": "FHWA13",
            "cat_00": 0,
            "cat_01": 2,
            "cat_02": 3,
            "cat_04": 3,
            "cat_05": 4,
            "cat_06": 4,
            "cat_07": 4,
            "cat_08": 1,
            "cat_09": 5,
            "cat_10": 7,
            "cat_11": 6,
            "cat_12": 7,
            "cat_13": 7,
            "cat_14": 7,
        },
        {
            "name": "SPCH13",
            "cat_00": 0,
            "cat_01": 2,
            "cat_02": 3,
            "cat_04": 3,
            "cat_05": 4,
            "cat_06": 4,
            "cat_07": 4,
            "cat_08": 1,
            "cat_09": 5,
            "cat_10": 6,
            "cat_11": 7,
            "cat_12": 6,
            "cat_13": 6,
            "cat_14": 7,
        },
        {
            "name": "EUR6",
            "cat_00": 0,
            "cat_01": 2,
            "cat_02": 3,
            "cat_04": 4,
            "cat_05": 5,
            "cat_06": 6,
            "cat_07": 1,
        },
        {
            "name": "SPCH7",
            "cat_00": 0,
            "cat_01": 2,
            "cat_02": 3,
            "cat_04": 4,
            "cat_05": 1,
            "cat_06": 5,
            "cat_07": 6,
            "cat_08": 7,
        },
    ]

    for u in updates:
        try:
            obj = ClassModel.objects.using(db_alias).get(name=u["name"])
            for field, value in u.items():
                if field != "name":
                    setattr(obj, field, value)
            obj.save()
        except ClassModel.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "comptages",
            "0029_class_cat_00_class_cat_01_class_cat_02_class_cat_03_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(existing_classes_values),
    ]
