# Generated by Django 5.2.5 on 2025-08-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0030_existing_classes_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorTypeSection',
        ),
    ]
