# Generated by Django 5.2.5 on 2025-08-25 07:03

from django.db import migrations


def fix_classes_values(apps, schema_editor):
    """Sets values for existing classes"""
    ClassModel = apps.get_model("comptages", "Class")
    db_alias = schema_editor.connection.alias
    updates = [
        {
            "name": "Volume1",
            "tabs_to_delete": [
                "SWISS10_H",
                "SWISS10_G",
                "SWISS7_H",
                "SWISS7_G",
                "EUR6_H",
                "EUR6_G",
            ],
        },
        {
            "name": "SWISS7",
            "tabs_to_delete": ["SWISS10_H", "SWISS10_G", "EUR6_H", "EUR6_G"],
        },
        {
            "name": "SWISS10",
            "tabs_to_delete": ["SWISS7_H", "SWISS7_G", "EUR6_H", "EUR6_G"],
        },
        {
            "name": "FHWA13",
            "cat_03": 3,
            "cat_04": 4,
            "cat_05": 4,
            "cat_06": 4,
            "cat_07": 1,
            "cat_08": 5,
            "cat_09": 7,
            "cat_10": 6,
            "cat_11": 7,
            "cat_12": 7,
            "cat_13": 7,
            "cat_14": 0,
            "tabs_to_delete": ["SWISS10_H", "SWISS10_G", "EUR6_H", "EUR6_G"],
            "to_be_converted": True,
        },
        {
            "name": "SPCH13",
            "cat_03": 3,
            "cat_04": 4,
            "cat_05": 4,
            "cat_06": 4,
            "cat_07": 1,
            "cat_08": 5,
            "cat_09": 6,
            "cat_10": 7,
            "cat_11": 6,
            "cat_12": 6,
            "cat_13": 7,
            "cat_14": 0,
            "tabs_to_delete": ["SWISS10_H", "SWISS10_G", "EUR6_H", "EUR6_G"],
            "to_be_converted": True,
        },
        {
            "name": "EUR6",
            "cat_03": 4,
            "cat_04": 5,
            "cat_05": 6,
            "cat_06": 1,
            "cat_07": 0,
            "tabs_to_delete": ["SWISS10_H", "SWISS10_G", "SWISS7_H", "SWISS7_G"],
            "to_be_converted": True,
        },
        {
            "name": "SPCH7",
            "cat_03": 4,
            "cat_04": 1,
            "cat_05": 5,
            "cat_06": 6,
            "cat_07": 7,
            "cat_08": 0,
            "tabs_to_delete": ["SWISS10_H", "SWISS10_G", "EUR6_H", "EUR6_G"],
            "to_be_converted": True,
        },
    ]

    for u in updates:
        try:
            obj = ClassModel.objects.using(db_alias).get(name=u["name"])
            for field, value in u.items():
                if field != "name":
                    setattr(obj, field, value)
            obj.save()
        except ClassModel.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("comptages", "0031_delete_sensortypesection"),
    ]

    operations = [
        migrations.RunPython(fix_classes_values),
    ]
