# Generated by Django 5.2.5 on 2025-08-26 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptages", "0033_alter_class_tabs_to_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="tabs_to_delete",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=90, null=True),
                default=list,
                size=None,
            ),
        ),
    ]
